name: robot-mood-classification-service
services:
  api:
    build: .
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=30031
      - DEBUG=${DEBUG:-false}
    ports:
      - "30031:30031"
    networks:
      - robot_mood_classification
networks:
  robot_mood_classification:
    driver: bridge
    ipam:
      config:
        - subnet: 10.250.0.0/24
