version: "3.11"
services:
  api:
    build: .
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-openai/gpt-oss-20b}
      - GROQ_TIMEOUT=${GROQ_TIMEOUT:-10.0}
      - API_HOST=0.0.0.0
      - API_PORT=30031
      - DEBUG=${DEBUG:-false}
    ports:
      - "30031:30031"

networks:
  name-network:               # tên mạng bạn tạo
    driver: bridge              # kiểu mạng: bridge (mặc định của Docker)
    ipam:                       # IP Address Management - quản lý dải IP
      driver: default
      config:
        - subnet: 10.200.0.0/24 # dải mạng (CIDR) dùng cho network này
          gateway: 10.200.0.1   # địa chỉ gateway (cổng mặc định) của network